### ISSUE TITLE
Regex Custom Block Support

### ISSUE THREAD

**Issue by MRog40** [gpanders/vim-medieval#1]
I've started using the static website generator Hugo which uses Go templates for user defined shortcodes.

With this use case in mind, it would be great if there was another variable where users could specify regex to select any type of block they wanted.

In .vimrc:
```
" Opening/Closing pair (in case that's needed)
let g:medieval_output_blocks = [
    ["```", "```"],
    ["$$", "$$"],
    ["{{<\s[\S]*\s>}}", "{{<\s\/[\S]*\s>}}"]
]
```

This would allow me to use it like this:
````
<!-- target: math -->
```python
print(r"\text{Hello KaTeX!}")
```

<!-- name: math -->
{{< katex >}}
\text{Hello KaTeX!}
{{< /katex >}}
````

**Comment by AceofSpades5757** [comment]
That sounds kinda cool.

**Comment by gpanders** [comment]
Seems reasonable. I just pushed aefad55c1e0d4726e8018ece1c32b865a0328d1b. Give that a try and let me know if you have any issues.

**Comment by gpanders** [comment]
Going to close this as it's now been implemented. If you find a bug or if it doesn't work as expected, feel free to open a new issue.
