### ISSUE TITLE
[Feature request] Add a hook or event at end of evaluation

### ISSUE THREAD

**Issue by lervag** [gpanders/vim-medieval#13]
I use a rather _hacky_ trick to change the background color of code blocks by use of signs. I would like to refresh the signs to get the colors correct after doing `:EvalBlock`, but I find it hard to do in a good manner. It seems `:EvalBlock` runs in a background job and updates the target output when the job is complete. Thus, doing things like this won't work:

```vim
nmap <buffer> <leader>ar <plug>(medieval-eval)<cmd>:call UpdateMySigns()<cr>
```

I was hoping you could add either an event like `EvalBlockComplete`, or, perhaps better, a new entry to the `medieval#eval` option dictionary, e.g. `after`:

```vim
function! s:after(ctx, input)
  echo "EvalBlock is finished and file is updated."
endfunction

call medieval#eval('', #{after: function('s:after')})
```

Perhaps a help text like this:

```
		  after:	(function) A function to be called when
				evaluation completes, after the output is
				written to the target block. The function
				accepts two arguments: a "context" |Dict|
				containing the parameters used to evaluate the
				block and the result of the block evaluation
				as a list of lines.
```

I'm not sure if the context and output line arguments are necessary in this case, but I guess they won't hurt and allows further flexibility to the user?

**Comment by gpanders** [comment]
I added `'setup'` and `'complete'`callbacks in https://github.com/gpanders/vim-medieval/pull/10. Are those sufficient for your use case? If not, I could extend those.

**Comment by lervag** [comment]
No, these are not sufficient. The `'complete'` callback is close, but it executes _before_ the buffer is updated with the output. For my use, I need a callback that is called _after_ the buffer is updated.

**Comment by lervag** [comment]
I believe it could be implemented with a block similar to this:

https://github.com/gpanders/vim-medieval/blob/master/autoload/medieval.vim#L173-L175

but placed after here:

https://github.com/gpanders/vim-medieval/blob/master/autoload/medieval.vim#L219

**Comment by gpanders** [comment]
Ok, I can take a look at this soon. I’m also happy to review a PR.

**Comment by lervag** [comment]
There you go :)
