### ISSUE TITLE
Feature request: Asynchronous execution

### ISSUE THREAD

**Issue by yoctocell** [gpanders/vim-medieval#2]
Would it be possible to support asynchronous execution of code blocks in Neovim and Vim. So you could type something like

```markdown
```python :async
```

to make the execution async.

**Comment by gpanders** [comment]
I think this is a good idea, and I can't think of any reason why it shouldn't be async by default. I implemented this in https://github.com/gpanders/vim-medieval/commit/da8d36397090a41a23061de6a3b746843d3dd3b2 (on `master`), give it a try and let me know if it meets your needs or if you run into any bugs.

**Comment by yoctocell** [comment]
I works well in my experience, haven't noticed any bugs. Thanks for taking the time!
