### ISSUE TITLE
Idea: create wiki, or contrib folder, where users can contribute settings for common use cases

### ISSUE THREAD

**Issue by MartyLake** [gpanders/vim-medieval#22]
Hey gpanders, thanks for taking care of implementing custom fences and patterns.

Now that it works, I wonder where could be a place to contribute settings that "just works", sorted by use cases. I was thinking about a contrib folder in the documentation, but maybe a wiki section in the github project is best suited.

Do you have any preference ?

The exact section I want to add is this
```
## How to configure vim-medieval with vim-wiki

    Plugin 'gpanders/vim-medieval'
    let g:medieval_langs = ['python=python3', 'sh', 'bash']
    let g:medieval_fences = [#{start: '{{{\(\a\+\)', end: '}}}', lang: 1 }]
    let g:medieval_option_pat = {}
    let g:medieval_option_pat.vimwiki = '^%%\s*'
    let g:medieval_option_fmt = {}
    let g:medieval_option_fmt.vimwiki = '%%%% %s'
```

Best.

**Comment by gpanders** [comment]
I’ve just made the wiki on this repo publicly editable so you should be able to add that now. 

The wiki doesn’t have any content right now, so yours will be the first addition.

**Comment by gpanders** [comment]
Will close this issue since there's no further action required. If you have any trouble modifying the wiki, let me know.

**Comment by MartyLake** [comment]
Thanks! created it a first page at https://github.com/gpanders/vim-medieval/wiki
since there is only one example, i put it here. If more are needed, it will be time to organise it a bit.

**Comment by MartyLake** [comment]
Hey, your tool is now listed in https://vimwiki.github.io/vimwikiwiki/Related%20Tools.html 🎉 
Thanks again for helping me get your extension compatible with vimwiki, I am using it quite a lot these days.
