### ISSUE TITLE
`:EvalBlock` not working

### ISSUE THREAD

**Issue by dalbandea** [gpanders/vim-medieval#6]
Hi. As I mentioned in the feature-request, `:EvalBlock` is not working for me.

### My configuration:
```vim
Plug 'gpanders/vim-medieval', { 'branch': 'master' }
let g:medieval_langs = ['python', 'sh', 'console=bash']
```

### Minimal Example:
````markdown
<!-- target: output -->
```python
print("hi")
```

<!-- name: output -->
```
```

````

- Running `:EvalBlock` does nothing.
- Running `:EvalBlock!` results, as expected, in
````markdown
<!-- target: output -->
```python
hi
```

<!-- name: output -->
```
```

````
- Running `:EvalBlock output` results, as expected, in
````markdown
<!-- target: output -->
```python
print("hi")
```

<!-- name: output -->
```
hi
```

````

I don't know how to debug this to pin down the problem, but if you tell me I can try stuff.

**Comment by gpanders** [comment]
Unfortunately I'm not able to reproduce this. Can you tell me what version of Vim you're using?

Could you also try using a minimal vimrc where you only install vim-medieval and no other plugins?

**Comment by dalbandea** [comment]
Vim version: 8.1.2269

I created a minimal `medieval_vimrc` file:
```vim
" Specify a directory for plugins
" - For Neovim: stdpath('data') . '/plugged'
" - Avoid using standard Vim directory names like 'plugin'
call plug#begin('~/.vim/plugged')


"" ============ MARKDOWN PLUGINS ============== 

" Run code blocks of markdown. Allows to run more than one block.
Plug 'gpanders/vim-medieval', { 'branch': 'master' }
let g:medieval_langs = ['python', 'sh', 'console=bash']

"" ===========================================



call plug#end()

filetype plugin indent on
```

I initiated vim using `vim -N -u "/home/david/.vim/medieval_vimrc" test2.md`, with `test2.md` being
````markdown
<-- target: output -->
```python
print(1+1)
```
<-- name: output -->
```
```
````

- `:EvalBlock!` works as expected.
- `:EvalBlock output` now does nothing.
- `:EvalBlock` opens another buffer with the name `[Scratch]` with the result of the evaluation.

![EvalBlock](https://user-images.githubusercontent.com/56197249/109319950-c2bf5280-784f-11eb-8b91-d97ba111c38b.png)

**Comment by gpanders** [comment]
Ah, the issue is that your HTML comments are invalid :)

Change `<--` to `<!--` and everything should work.

**Comment by dalbandea** [comment]
Uf, I'm lost without highlighting haha. It works indeed. And I just pinned down the problem. If
```vim
set clipboard=unnamed
```
is set on the vimrc, `:EvalBlock` does not work.

Minimal vimrc:
````vim
" Specify a directory for plugins
" - For Neovim: stdpath('data') . '/plugged'
" - Avoid using standard Vim directory names like 'plugin'
call plug#begin('~/.vim/plugged')


" To use system clipboard (register *) as default. Copying with y will copy
" something to the clipboard. 
set clipboard=unnamed

"" ============ MARKDOWN PLUGINS ============== 

" Run code blocks of markdown. Allows to run more than one block.
Plug 'gpanders/vim-medieval', { 'branch': 'master' }
let g:medieval_langs = ['python', 'sh', 'console=bash']

"" ===========================================



call plug#end()

filetype plugin indent on
````

Markdown test file:
````markdown
<!-- target: output -->
```python
print(1+1)
```
<!-- name: output -->
```
```
````

**Comment by gpanders** [comment]
Ah good find, yes I can reproduce that now. Let me take a look.

**Comment by gpanders** [comment]
Ok I think I found the issue. Medieval has support for copying the output to a register, so that if you have a keybinding set up (`Z!`) for example, you can copy the output of the execution to a register using `"+Z!`.

When the clipboard option is set to "unnamed", then the `v:register` variable in Vim is *always* set to `+`, so it looks to Medieval like you're always trying to copy the output to a register. So all I had to do was add a check to see if the clipboard option is set to "unnamed" and handle that case appropriately.

The fix is on master now, please let me know if it doesn't work for you.

**Comment by dalbandea** [comment]
It works for me now.
