### ISSUE TITLE
Feature request: create result code block if "target" does not match any "name"

### ISSUE THREAD

**Issue by dalbandea** [gpanders/vim-medieval#7]
Hi again! And thank you for the implementation of the dependent blocks!

I have a suggestion to save some time writing while using the plugin. Now, when you have something like 

````markdown
<!-- target: output -->
```sh
echo "hi"
```
````

and nothing else, and you run `:EvalBlock`, you get the message `medieval: Couldn't find block "output"` and nothing happens. But a code block with a `target` will always need an output cell with the specified name, so why not create it automatically if it does not find any? 

### Suggested behavior:
- Initial code block:
````markdown
<!-- target: output -->
```sh
echo "hi"
```
````
- Run `:EvalBlock`. If there is no matching "output" cell, create it with the execution results inside:
````markdown
<!-- target: output -->
```sh
echo "hi"
```

<!-- name: output -->
```
hi
```
````

**Comment by gpanders** [comment]
Thanks for the suggestion! I like it and I just pushed d989503 that implements this.
