### ISSUE TITLE
[Question] Feature comparison with org-babel.

### ISSUE THREAD

**Issue by nbCloud91** [gpanders/vim-medieval#8]
I was on the lookout for tools to replace the various functionalities of Emacs' org-mode. An important piece of org-mode is
org-babel which is for literate programming. In case you are familiar with org-babel, how close do you feel vim-medieval is,
to having feature parity with it? Example of a nifty thing org-babel does: there's this option to *tangle* a code-block(or blocks in
a single language) into a separate source file for that language, this is handy in certain situations, the code block can then be edited in a separate buffer with all the LSP(and other) functionality associated with that filetype, once you are done editing the changes could be saved across both the copies (the tangled source-file and the original org-document).

**Comment by gpanders** [comment]
Re-implementing org-mode in Vim is not a goal of vim-medieval, and for the most part I consider this plugin feature complete. That said, I do think the ability to target a buffer as the output of a code block could be useful, though I don't think this is exactly what you're asking about.

**Comment by nbCloud91** [comment]
I think I did not explain it correctly. When I said I want to replicate org-mode, I did NOT mean using one tool, I meant replication of each small part of org using different tools. (That is one of the arguments against using Emacs, that it is not very unixy). So when I asked about "feature parity" I did not mean feature parity with whole of org mode, but only feature parity with the org-babel part of it. Of course I do not expect vim-medieval to have all functionalities of org mode itself. 
The specific feature of org-babel I was looking for, is tangling. Which allows for generation of source files in different languages from the code blocks within a markup document. See for example [nvim-literate](https://github.com/shoumodip/nvim-literate)

**Comment by gpanders** [comment]
So I'll be honest, I was all ready to turn this down as scope creep and claiming that it would add a lot of bloat, but it actually turns out that it was incredibly easy to implement and fit right in with the model that Medieval uses. I just pushed 2e96a19 that implements this feature. Please give it a try and re-open a new issue if you find any bugs!

**Comment by nbCloud91** [comment]
I just tested some simple stuff, working as expected! Thanks for implementing this feature.
